#! /bin/bash
filename="config"

if [ "$1" == "default" ]
	then
		echo default is set
else
	if [ "$1" != "" ]
		then
			filename="$1"
	fi

	hostname=`cat /etc/hostname`
	cat default-base-config *$hostname* >> $filename
fi

